### PR TITLE
Change group / org info to Syndesis.

### PR DESCRIPTION
**Pull request by cunningt**

### CODE REVIEW

**Comment by cunningt** [comment]
Jimmi made a comment on https://github.com/syndesisio/keycloak-openshift/pull/1 that we should be using io.syndesis for all syndesis projects.

**Comment by jimmidyson** [comment]
Did you mean to close this?

**Comment by cunningt** [comment]
I missed the child modules and I didn't want it to get processed until I got the commit fixed up, will resubmit.

**Comment by jimmidyson** [comment]
ah ok cool thanks.

**Pull request closed without merging**
